const everyPokemon = {
bulbasaur: {
    indexNumber: "001",
    pokemonName: "Bulbasaur",
    sprite: "https://img.pokemondb.net/sprites/sword-shield/icon/bulbasaur.png",
    pokemonIcon: "https://img.pokemondb.net/sprites/sword-shield/icon/bulbasaur.png",
    pokemonType: "Grass/Poison",
    pokemonPrimaryType: "Grass",
    pokemonSecondaryType: "Poison",
    health: "",
    attack: "",
    defense: "",
    specialAttack: "",
    specialDefense: "",
    speed: "",
    totalStats: "",
},
ivysaur: {
    indexNumber: "002",
    pokemonName: "Ivysaur",
    sprite: "https://img.pokemondb.net/sprites/sword-shield/icon/ivysaur.png",
    pokemonIcon: "https://img.pokemondb.net/sprites/sword-shield/icon/ivysaur.png",
    pokemonType: "Grass/Poison",
    pokemonPrimaryType: "Grass",
    pokemonSecondaryType: "Poison",
    health: "",
    attack: "",
    defense: "",
    specialAttack: "",
    specialDefense: "",
    speed: "",
    totalStats: "",
},

}
export default everyPokemon;